### PR TITLE
Removed shrinkwrap creation from the project.

### PR DESCRIPTION
**Pull request by BrianGilbert**
@ezzatron here is the PR to remove shrinkwrap creation

### CODE REVIEW

**Comment by ezzatron** [comment]
Heh, seems like a pretty easy fix! Nice.

I'll give it a quick go now. Have you tried this for your use-case?

**Comment by BrianGilbert** [comment]
Yes I have tried it on our project across multiple users and confirmed it works as expected

**Comment by ezzatron** [comment]
For reference, I have a few [fixture repos under my personal account](https://github.com/ezzatron?utf8=%E2%9C%93&tab=repositories&q=composer-npm-bridge-fixture&type=&language=) that can be useful for testing this package in all the scenarios under which it needs to work.

**Comment by ezzatron** [comment]
I'm going to manually pull this into a branch under `eloquent` so I can test it more easily. It might mark this PR as merged.

**Comment by BrianGilbert** [comment]
no problems, any way to easily tell when it's available for use? (wher in .au are you based btw? Melbourne myself)

**Comment by ezzatron** [comment]
Looks like it didn't get marked as merged, so you should get notified when I merge this (provided there's no issues). I'll probably roll a new release shortly after and update this task too. If you're really desperate, you could use `dev-npm-lock` as your constraint right now.

**Comment by BrianGilbert** [comment]
can wait a day or two.. cheers.

**Comment by ezzatron** [comment]
So I've encountered a small problem here, namely npm/npm#16967. Basically, `package-lock.json` gets modified by NPM when you run `npm install --production`. Supposedly the bug was recently fixed, but it isn't released as yet. This project uses `--production` in a few use cases.

I doubt it's going to cause major issues, but it will cause `package-lock.json` files to be in a modified state inside the `vendor` directory. Composer will warn about this when running `composer update`, which is not ideal, and will cause confusion for some users.

**Comment by BrianGilbert** [comment]
@ezzatron whats the easiest way for me to check this?  I just updated my npm version to 5.2.0 which came out yesterday..

**Comment by ezzatron** [comment]
To demonstrate:

    git clone git@github.com:ezzatron/composer-npm-bridge-fixture-intermediate.git
    cd composer-npm-bridge-fixture-intermediate
    composer install
    cd vendor/ezzatron/composer-npm-bridge-fixture-dependency
    git status
    git diff

**Comment by ezzatron** [comment]
But I'm pretty confident the fix is not out yet, it doesn't appear anywhere in NPM's [release notes](https://github.com/npm/npm/releases) and was only fixed about a week ago.

**Comment by BrianGilbert** [comment]
based on the commit history the it looks like it was committed to release-next 11 days ago, and anything there was packaged into the release that was pushed yesterday https://github.com/npm/npm/commits/release-next

Given I've installed the latest npm, I figure I should be able to confirm this, just not sure steps I would need to do to test?

**Comment by ezzatron** [comment]
Just tried it with NPM 5.2.0 myself, and that particular issue to do with `--production` does appear to be fixed.

There's still the minor annoyance that NPM will modify `package-lock.json` if there's been a change to the format of that file. This happened to me when I upgraded NPM to try again. I don't know if there's anything that can reasonably be done about it though. It just means that if `package-lock.json` was committed with one version of NPM, and the installed with another, you'll end up with modifications in your `vendor` directory.

A couple of comments above, I pasted the steps to demonstrate. If `git status` or `git diff` show differences at the end there, then NPM has modified something.

**Comment by BrianGilbert** [comment]
great, does that mean this is merge-able now then?

**Comment by ezzatron** [comment]
Released in [4.0.0](https://github.com/eloquent/composer-npm-bridge/releases/4.0.0).

**Pull request merged**
